### ISSUE TITLE
Suggestions to expand the readme

### ISSUE THREAD

**Issue by larixk** [RandomStudio/tether#14]
Some notes on the Tether README:

- Could we have two sentences on the idea of a pub/sub architecture and its general benefits? Feels like we jump from mentioning MQTT and very high-level benefits in the intro, and then after the index to the choice for MQTT specifically. I feel that the sort of middle layer of ‘pub/sub being a pattern that is common and good for this’ could be added.
- The grouping of the agents (mostly input, mostly output, both and utilities) was a bit confusing to me. I think I understand these are used as examples and aren’t actually structural differences, but especially the single utility (isn’t a scheduler mostly input) makes me feel like there are some semantics that I don’t fully get. Maybe good to simplify the categories or explain why we mention them in groups. (Also isn’t there a generic logger you can connect as an agent?)
- Plug Name concept could use some examples
- Would be great to have an example of how to set up a minimal instance (maybe a broker, minimal gui, and a logger/visualisation) but understand that would require some work in other repos as well.
- Would be great to have a list of our related repos in the Tether ecosystem
- Would be great to have a mention of how to contribute to the Tether ecosystem (developing Agents, contributing to the main repo), and how we generally want to go about this (never commit to main directly, open MRs for you and Ralph to review, code standards if we have them, etc.)

Just some pointers at what could be added to be picked up later (let me know if you want any of this to be an official project, it definitely could), but already in a really good state.

**Comment by anselanza** [comment]
@larixk (and anyone else), please take a look at https://github.com/RandomStudio/tether/blob/feature/improve-docs/README.md where I tried to address the first point (pub/sub architecture) much more directly.

I will attempt to address the other issues later.

**Comment by anselanza** [comment]
@larixk "Grouping of agents" section has been tidied up. The inclusion of the "utilities" section was confusing in this context.

The pure generic logging utility (`tether-receive`) and generic sending utility (`tether-send`) don't really fit here, as they are not really true "agents". I will try to mention them separately in a different section.

**Comment by anselanza** [comment]
@larixk Big restructuring now on the `improve-docs` branch: in particular, a whole section named "Understanding Tether" has been separated from the more detailed "Formally defining a Tether System" section. 

This hopefully explains terminology and approach much better than before.

**Comment by anselanza** [comment]
Oh, and added a "Quick start" section.

**Comment by anselanza** [comment]
Closing this for now, except that the following will be split into another issue:

> Would be great to have a mention of how to contribute to the Tether ecosystem (developing Agents, contributing to the main repo), and how we generally want to go about this (never commit to main directly, open MRs for you and Ralph to review, code standards if we have them, etc.)
