### ISSUE TITLE
Revise check_messages() return value in Rust base agent to allow for more precise matching

### ISSUE THREAD

**Issue by ralphkok** [RandomStudio/tether#21]
The `check_messages()` function on the Rust base agent currently returns a tuple containing the plug name and the message that was received.
In order to allow more flexibility and precision when matching incoming messages to plugs, it might make more sense to be able to match messages and plugs instead of automatically parsing out the plug name from the message topic.

**Comment by anselanza** [comment]
Addressed by #35
