### ISSUE TITLE
Tether util cli args should omit `tether.`

### ISSUE THREAD

**Issue by ralphkok** [RandomStudio/tether#32]
When running a tether cli util, connection details are provided using `tether.` prefixes, e.g.
```
tether --tether.host localhost --tether.username tether --tether.password sp_ceB0ss!
```
This is unnecessarily verbose, as they're arguments provided to the `tether` utility.
Proposal: remove the `tether.` prefix for these arguments for brevity.

**Comment by anselanza** [comment]
Added this into pull request #31
