### ISSUE TITLE
Docs should be updated with GitHub package installation instructions

### ISSUE THREAD

**Issue by anselanza** [RandomStudio/tether#6]
Also check for tether-cli tools, which are on GitHub packages but docs still refer to registry.tether-io.dev

**Comment by kyunwang** [comment]
+1 bump

**Comment by anselanza** [comment]
Damn, this is annoying (from https://stackoverflow.com/questions/72732582/using-github-packages-without-personal-access-token):

> As early as [2019-10-20](https://web.archive.org/web/20211215173925/https://github.community/t/download-from-github-package-registry-without-authentication/14407), people have requested github to remove PATs as a requirement for mainly downloading public packages.
>The idea is that users of libraries should not need to have a github account to access a developer's package.
>Sadly, the request for pat-less package downloads was not granted by Github to this day.

This makes it very awkward to distribute the Tether Agent NPM package, even though the repo itself is public (as it should be) and we want to make it easy as possible to download and install.
